### PR TITLE
Discussion on HBvsNI results in the report

### PR DESCRIPTION
**Pull request by kooroshg1**
Also small modification to the code.

### CODE REVIEW

**Comment by AnushaAnisetti** [comment]
I'm having some conflict issues after merging your recent pull request. I need to look into it.. as I'm unable to submit my changes.

**Comment by kooroshg1** [comment]
You first need to pull, and then push.

**Comment by kooroshg1** [comment]
Were you able to fix the merging issue?

**Comment by AnushaAnisetti** [comment]
Yes I did!

Sincerely,

Anusha Anisetti

PhD Candidate

**Pull request merged**
